# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      run:
        echo Starting the tests:
        mkdir bin
        mkdir lib
        curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.5.2/junit-platform-console-standalone-1.5.2.jar -o lib/junit-platform-console-standalone-1.5.2.jar
        javac -d bin/ src/Calculator.java
        javac -d bin -cp bin:lib/junit-platform-console-standalone-1.5.2.jar test/*
        java -jar lib/junit-platform-console-standalone-1.5.2.jar --class-path bin --scan-class-path
     uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
